/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fef7fc",
        "on-primary-fixed-variant": "#533d69",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#42627d",
        "outline": "#7b757e",
        "primary": "#1c0832",
        "surface-tint": "#6b5583",
        "tertiary-container": "#b6ac75",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e7e1e5",
        "error": "#ba1a1a",
        "primary-fixed": "#efdbff",
        "inverse-surface": "#322f33",
        "tertiary-fixed": "#efe3a8",
        "surface-dim": "#ded8dd",
        "on-surface": "#1d1b1e",
        "secondary-container": "#bddefd",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f5eff3",
        "on-tertiary-container": "#474014",
        "background": "#fef7fc",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#25113b",
        "secondary-fixed-dim": "#a9cae9",
        "on-tertiary-fixed-variant": "#4e471a",
        "primary-fixed-dim": "#d7bcf1",
        "surface-container-high": "#ede6eb",
        "outline-variant": "#ccc4ce",
        "surface-container": "#f2ecf1",
        "on-primary": "#ffffff",
        "primary-container": "#321e48",
        "on-tertiary-fixed": "#201c00",
        "inverse-primary": "#d7bcf1",
        "secondary-fixed": "#cce5ff",
        "surface": "#fef7fc",
        "on-surface-variant": "#4a454d",
        "tertiary-fixed-dim": "#d2c78e",
        "on-secondary-fixed": "#001e31",
        "secondary": "#41627c",
        "surface-container-low": "#f8f2f6",
        "on-secondary-fixed-variant": "#294a64",
        "tertiary": "#675f30",
        "on-primary-container": "#9d85b6",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1d1b1e",
        "surface-variant": "#e7e1e5",
        "brand-purple": "#2563eb",
        "brand-light": "#121212",
        "brand-dark": "#ffffff",
        "brand-gradient-start": "#1e3a8a",
        "brand-gradient-end": "#3b82f6",
        "brand-card-bg": "#1e1e1e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "24px",
        "margin-mobile": "20px",
        "container-padding": "20px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter-md": "16px",
        "unit": "4px"
      },
      fontFamily: {
        "body-md": ["System"],
        "body-lg": ["System"],
        "headline-xl-mobile": ["System"],
        "label-md": ["System"],
        "headline-xl": ["System"],
        "headline-lg": ["System"],
        "headline-md": ["System"],
        "label-sm": ["System"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
